### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [GustavGroenborg/greencastle-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by GustavGroenborg** [comment]
Done as of https://github.com/GustavGroenborg/greencastle-zsh-theme/commit/596af2195b58a0c7e6d5c8223b0b4ae03f1e221a
